### ISSUE TITLE
Why multiply 1.10?

### ISSUE THREAD

**Issue by clicpilot** [lovasoa/bloomfilter#3]
Hi I looked to the test and have a question about why we need multiply expectedRate with 1.1? 

https://github.com/lovasoa/bloomfilter/blob/7d022145d6dd631b69004b0e834908e333f60ed3/src/test/java/Test.java#L59

**Comment by lovasoa** [comment]
I wrote this code a long time ago, but this seems to be because the actual error rate only asymptotically converges to what the formula gives when the number of elements in the filter is large. This is not an exact formula that gives the exact number of false positives whatever the elements are.
